listen_addresses = '*'
wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on
wal_keep_size = 128MB
primary_conninfo = 'host=192.168.1.15 port=5432 user=replicator password=replicator_pass'
